version: '3.9'
services:
  prismatica:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env  # Import environment variables from .env file
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}  # Reference variables from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # Change to 5433 on the host
    env_file:
      - .env  # (Optional) Load the same .env file here for consistency
